// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type HomeDocumentDataSlicesSlice = never

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Curriculum Vitae field in *Home*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Add you Curriculum/Resume
   * - **API ID Path**: home.curriculum
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  curriculum: prismic.LinkToMediaField

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

/**
 * Item in *Project → Team*
 */
export interface ProjectDocumentDataTeamItem {
  /**
   * Member Name field in *Project → Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Rocketseat
   * - **API ID Path**: project.team[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Role field in *Project → Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ux/UI Designer
   * - **API ID Path**: project.team[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField
}

/**
 * Item in *Project → Technologies*
 */
export interface ProjectDocumentDataTechsItem {
  /**
   * Technology field in *Project → Technologies*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.techs[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<'technology'>
}

type ProjectDocumentDataSlicesSlice = never

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Highlight field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.isHighlight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isHighlight: prismic.BooleanField

  /**
   * Name field in *Project*
   *
   * - **Field Type**: Title
   * - **Placeholder**: The Project name
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField

  /**
   * Cover Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>

  /**
   * Start Date field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.startDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  startDate: prismic.DateField

  /**
   * End Date field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.endDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  endDate: prismic.DateField

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A small description of the project
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * My Role field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Full-stack developer
   * - **API ID Path**: project.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField

  /**
   * Team field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.team[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team: prismic.GroupField<Simplify<ProjectDocumentDataTeamItem>>

  /**
   * Story field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Tell more about the project, how it started, challenges and differences...
   * - **API ID Path**: project.story
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  story: prismic.RichTextField

  /**
   * Live demo field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://farrel.tech
   * - **API ID Path**: project.liveDemo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  liveDemo: prismic.LinkField

  /**
   * Github Repository field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://github.com/farreltobias/repo_name
   * - **API ID Path**: project.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField

  /**
   * Technologies field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.techs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  techs: prismic.GroupField<Simplify<ProjectDocumentDataTechsItem>>

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, 'project', Lang>

/**
 * Content for Technology documents
 */
interface TechnologyDocumentData {
  /**
   * highlight field in *Technology*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: technology.isHighlight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isHighlight: prismic.BooleanField

  /**
   * Name field in *Technology*
   *
   * - **Field Type**: Text
   * - **Placeholder**: React
   * - **API ID Path**: technology.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Icon Name (DevIcon) field in *Technology*
   *
   * - **Field Type**: Text
   * - **Placeholder**: devicon-react-original
   * - **API ID Path**: technology.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField

  /**
   * Theme field in *Technology*
   *
   * - **Field Type**: Color
   * - **Placeholder**: #61dafb
   * - **API ID Path**: technology.theme
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme: prismic.ColorField

  /**
   * Show in filter field in *Technology*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: technology.filter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  filter: prismic.BooleanField
}

/**
 * Technology document from Prismic
 *
 * - **API ID**: `technology`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechnologyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TechnologyDocumentData>,
    'technology',
    Lang
  >

export type AllDocumentTypes =
  | HomeDocument
  | ProjectDocument
  | TechnologyDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AllDocumentTypes,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectDocumentDataTeamItem,
      ProjectDocumentDataTechsItem,
      TechnologyDocument,
      TechnologyDocumentData,
    }
  }
}
